# This file provides instructions for packaging.

`MooX-ClassAttribute`
	perl_version_from m`MooX::ClassAttribute`;
	version_from      m`MooX::ClassAttribute`;
	readme_from       m`MooX::ClassAttribute`;
	requires          p`Moo 1.000000`;
	recommends        p`MooseX::ClassAttribute 0`;
	requires          p`Role::Tiny 0`;
	requires          p`Sub::Exporter::Progressive 0`;
	.

