# This file provides instructions for packaging.

`MooX-ClassAttribute`
	perl_version_from m`MooX::ClassAttribute`;
	version_from      m`MooX::ClassAttribute`;
	readme_from       m`MooX::ClassAttribute`;
	test_requires     p`Test::More 0.61` ;
	.

